### ISSUE TITLE
Additional transmission-daemon processes spawned for each blocklist updates

### ISSUE THREAD

**Issue by lharsfalvi** [linuxserver/docker-transmission#91]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

There is an optional feature to periodically update the blocklist, which (when enabled) would happen once a day at 3AM. The /config/blocklist-update.sh script downloads the current blocklist file, extracts it, then makes an attempt to have transmission-daemon reload its configs.

## Current Behavior

As it looks, whenever the updater script is executed, a new transmission-daemon process is spawned, with the previously existing ones kept.
## Steps to Reproduce

magrathea:~/docker/transmission$ docker-compose up -d
Creating network "transmission_default" with the default driver
Creating transmission ... done
magrathea:~/docker/transmission$ docker exec -it transmission /bin/bash
root@7538d656c2c3:/# ps
PID   USER     TIME  COMMAND
    1 root      0:00 s6-svscan -t0 /var/run/s6/services
   32 root      0:00 s6-supervise s6-fdholderd
  247 root      0:00 s6-supervise cron
  248 root      0:00 s6-supervise transmission
  250 root      0:00 bash ./run
  251 root      0:00 /usr/sbin/crond -f -S -l 0 -c /etc/crontabs
**  257 abc       0:00 /usr/bin/transmission-daemon -g /config -c /watch -f **
  273 root      0:00 /bin/bash
  281 root      0:00 ps
root@7538d656c2c3:/# /config/blocklist-update.sh 
root@7538d656c2c3:/# ps
PID   USER     TIME  COMMAND
    1 root      0:00 s6-svscan -t0 /var/run/s6/services
   32 root      0:00 s6-supervise s6-fdholderd
  247 root      0:00 s6-supervise cron
  248 root      0:00 s6-supervise transmission
  251 root      0:00 /usr/sbin/crond -f -S -l 0 -c /etc/crontabs
**  257 abc       0:01 /usr/bin/transmission-daemon -g /config -c /watch -f **
  273 root      0:00 /bin/bash
  360 root      0:00 bash ./run
**  362 abc       0:02 /usr/bin/transmission-daemon -g /config -c /watch -f **
  366 root      0:00 ps
root@7538d656c2c3:/# /config/blocklist-update.sh 
root@7538d656c2c3:/# ps
PID   USER     TIME  COMMAND
    1 root      0:00 s6-svscan -t0 /var/run/s6/services
   32 root      0:00 s6-supervise s6-fdholderd
  247 root      0:00 s6-supervise cron
  248 root      0:00 s6-supervise transmission
  251 root      0:00 /usr/sbin/crond -f -S -l 0 -c /etc/crontabs
  ** 257 abc       0:17 /usr/bin/transmission-daemon -g /config -c /watch -f **
  273 root      0:00 /bin/bash
  ** 362 abc       0:09 /usr/bin/transmission-daemon -g /config -c /watch -f **
  689 root      0:00 bash ./run
  ** 691 abc       0:01 /usr/bin/transmission-daemon -g /config -c /watch -f **
  698 root      0:00 ps

I don't exactly know where/when the bug was introduced. Image #5682f5743e70 (14 months old according to Docker), as one example, didn't show this problem.

As it looks, the problem happens with this line in /config/blocklist-update.sh :

s6-svc -h /var/run/s6/services/transmission

The problem (ie. spawning an extra transmission-daemon process) can be triggered by executing this command alone.

## Environment
**OS:**      Alpine 3.10.3
**CPU architecture:** x86_64      
**How docker service was installed:**      apk
magrathea:~# apk list|grep docker|grep installed
docker-bash-completion-18.09.8-r0 x86_64 {docker} (Apache-2.0) [installed]
docker-cli-18.09.8-r0 x86_64 {docker} (Apache-2.0) [installed]
docker-openrc-18.09.8-r0 x86_64 {docker} (Apache-2.0) [installed]
docker-doc-18.09.8-r0 x86_64 {docker} (Apache-2.0) [installed]
docker-engine-18.09.8-r0 x86_64 {docker} (Apache-2.0) [installed]
docker-18.09.8-r0 x86_64 {docker} (Apache-2.0) [installed]

I think the problem is not specific to any particular versions of docker. This machine has been kept updated regularly. The mentioned (14 months old) image has run flawlessly, at any given time. Updated versions of the transmission image that I had tried (I don't know exact specifics) after #5682f5743e70 all showed this problem.

## Command used to create docker container (run/create/compose/screenshot)

UIDs, user/pass, IP addresses, local paths etc. all censored.

version: "3"
services:
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    volumes:
      - /***/_config:/config
      - /***/foo:/downloads
      - /***/_watch:/watch
    ports:
      - "9091:9091"
      - "***:***"
      - "***:***/udp"
    environment:
      PGID: "***"
      PUID: "***"
      TZ: "Europe/Budapest"
      TRANSMISSION_WEB_HOME: "/transmission/"
      USER: "*****"
      PASS: "*****"
      S6_KILL_GRACETIME: "30000"
    restart:
      unless-stopped
    

## Docker logs

Specific IDs have been censored.

Syslog is used to collect docker's logs, thus the seemingly unusual format.

I have filtered the log snippet through grep -vE 'announce|variant|torrent|verify.c|net.c' as to get rid of any irrelevant junk.

I spun up the container at 23:45:06, executed /config/blocklist-update.sh from inside at around 23:46:05, then shut down the container (by docker-compose down) at 23:46:49.

2020-01-01T23:45:06+01:00 localhost.hq 564356623c6f[2656]: [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
2020-01-01T23:45:06+01:00 localhost.hq 564356623c6f[2656]: [s6-init] ensuring user provided files have correct perms...exited 0.
2020-01-01T23:45:06+01:00 localhost.hq 564356623c6f[2656]: [fix-attrs.d] applying ownership & permissions fixes...
2020-01-01T23:45:06+01:00 localhost.hq 564356623c6f[2656]: [fix-attrs.d] done.
2020-01-01T23:45:06+01:00 localhost.hq 564356623c6f[2656]: [cont-init.d] executing container initialization scripts...
2020-01-01T23:45:06+01:00 localhost.hq 564356623c6f[2656]: [cont-init.d] 01-envfile: executing... 
2020-01-01T23:45:06+01:00 localhost.hq 564356623c6f[2656]: [cont-init.d] 01-envfile: exited 0.
2020-01-01T23:45:06+01:00 localhost.hq 564356623c6f[2656]: [cont-init.d] 10-adduser: executing... 
2020-01-01T23:45:07+01:00 localhost.hq 564356623c6f[2656]: 
2020-01-01T23:45:07+01:00 localhost.hq 564356623c6f[2656]: -------------------------------------
2020-01-01T23:45:07+01:00 localhost.hq 564356623c6f[2656]:           _         ()
2020-01-01T23:45:07+01:00 localhost.hq 564356623c6f[2656]:          | |  ___   _    __
2020-01-01T23:45:07+01:00 localhost.hq 564356623c6f[2656]:          | | / __| | |  /  \ 
2020-01-01T23:45:07+01:00 localhost.hq 564356623c6f[2656]:          | | \__ \ | | | () |
2020-01-01T23:45:07+01:00 localhost.hq 564356623c6f[2656]:          |_| |___/ |_|  \__/
2020-01-01T23:45:07+01:00 localhost.hq 564356623c6f[2656]: 
2020-01-01T23:45:07+01:00 localhost.hq 564356623c6f[2656]: 
2020-01-01T23:45:07+01:00 localhost.hq 564356623c6f[2656]: Brought to you by linuxserver.io
2020-01-01T23:45:07+01:00 localhost.hq 564356623c6f[2656]: We gratefully accept donations at:
2020-01-01T23:45:07+01:00 localhost.hq 564356623c6f[2656]: https://www.linuxserver.io/donate/
2020-01-01T23:45:07+01:00 localhost.hq 564356623c6f[2656]: -------------------------------------
2020-01-01T23:45:07+01:00 localhost.hq 564356623c6f[2656]: GID/UID
2020-01-01T23:45:07+01:00 localhost.hq 564356623c6f[2656]: -------------------------------------
2020-01-01T23:45:07+01:00 localhost.hq 564356623c6f[2656]: 
2020-01-01T23:45:07+01:00 localhost.hq 564356623c6f[2656]: User uid:    ***
2020-01-01T23:45:07+01:00 localhost.hq 564356623c6f[2656]: User gid:    ***
2020-01-01T23:45:07+01:00 localhost.hq 564356623c6f[2656]: -------------------------------------
2020-01-01T23:45:07+01:00 localhost.hq 564356623c6f[2656]: 
2020-01-01T23:45:07+01:00 localhost.hq 564356623c6f[2656]: [cont-init.d] 10-adduser: exited 0.
2020-01-01T23:45:07+01:00 localhost.hq 564356623c6f[2656]: [cont-init.d] 20-config: executing... 
2020-01-01T23:45:07+01:00 localhost.hq 564356623c6f[2656]: [cont-init.d] 20-config: exited 0.
2020-01-01T23:45:07+01:00 localhost.hq 564356623c6f[2656]: [cont-init.d] 99-custom-files: executing... 
2020-01-01T23:45:07+01:00 localhost.hq 564356623c6f[2656]: [custom-init] no custom files found exiting...
2020-01-01T23:45:07+01:00 localhost.hq 564356623c6f[2656]: [cont-init.d] 99-custom-files: exited 0.
2020-01-01T23:45:07+01:00 localhost.hq 564356623c6f[2656]: [cont-init.d] done.
2020-01-01T23:45:07+01:00 localhost.hq 564356623c6f[2656]: [services.d] starting services
2020-01-01T23:45:07+01:00 localhost.hq 564356623c6f[2656]: [services.d] done.
2020-01-01T23:45:08+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:45:08.916] Transmission 2.94 (d8e60ee44f) started (session.c:740)
2020-01-01T23:45:08+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:45:08.917] RPC Server Adding address to whitelist: 127.0.0.1 (rpc-server.c:971)
2020-01-01T23:45:08+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:45:08.918] RPC Server Adding address to whitelist: *** (rpc-server.c:971)
2020-01-01T23:45:08+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:45:08.919] RPC Server Serving RPC and Web requests on port 127.0.0.1:9091/transmission/ (rpc-server.c:1213)
2020-01-01T23:45:08+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:45:08.920] RPC Server Whitelist enabled (rpc-server.c:1217)
2020-01-01T23:45:08+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:45:08.921] RPC Server Password required (rpc-server.c:1220)
2020-01-01T23:45:08+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:45:08.921] DHT Reusing old id (tr-dht.c:307)
2020-01-01T23:45:08+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:45:08.922] DHT Bootstrapping from 111 IPv4 nodes (tr-dht.c:156)
2020-01-01T23:45:08+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:45:08.923] Using settings from "/config" (daemon.c:528)
2020-01-01T23:45:08+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:45:08.925] transmission-daemon requiring authentication (daemon.c:554)
2020-01-01T23:45:08+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:45:08.926] Blocklist "blocklist.bin" contains 409833 entries (blocklist.c:100)
2020-01-01T23:45:08+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:45:08.931] Changed open file limit from 1048576 to 1024 (fdlimit.c:380)
2020-01-01T23:45:08+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:45:08.931] Port Forwarding (NAT-PMP) initnatpmp succeeded (0) (natpmp.c:70)
2020-01-01T23:45:08+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:45:08.931] Port Forwarding (NAT-PMP) sendpublicaddressrequest succeeded (2) (natpmp.c:70)
2020-01-01T23:45:16+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:45:16.916] Port Forwarding State changed from "Not forwarded" to "Starting" (port-forwarding.c:92)
2020-01-01T23:45:16+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:45:16.917] Port Forwarding State changed from "Starting" to "???" (port-forwarding.c:92)
2020-01-01T23:46:05+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:46:05.083] blocklist skipped invalid address at line 1 (blocklist.c:352)
2020-01-01T23:46:05+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:46:05.084] blocklist skipped invalid address at line 2 (blocklist.c:352)
2020-01-01T23:46:05+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:46:05.085] blocklist skipped invalid address at line 25378 (blocklist.c:352)
2020-01-01T23:46:05+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:46:05.085] blocklist skipped invalid address at line 25379 (blocklist.c:352)
...
2020-01-01T23:46:05+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:46:05.101] blocklist skipped invalid address at line 513052 (blocklist.c:352)
2020-01-01T23:46:05+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:46:05.101] Blocklist "blocklist.bin" updated with 409833 entries (blocklist.c:408)
2020-01-01T23:46:05+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:46:05.101] Blocklist "blocklist.bin" contains 409833 entries (blocklist.c:100)
2020-01-01T23:46:05+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:46:05.101] Transmission 2.94 (d8e60ee44f) started (session.c:740)
2020-01-01T23:46:05+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:46:05.101] RPC Server Adding address to whitelist: 127.0.0.1 (rpc-server.c:971)
2020-01-01T23:46:05+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:46:05.101] RPC Server Adding address to whitelist: *** (rpc-server.c:971)
2020-01-01T23:46:05+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:46:05.102] RPC Server Serving RPC and Web requests on port 127.0.0.1:9091/transmission/ (rpc-server.c:1213)
2020-01-01T23:46:05+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:46:05.102] RPC Server Whitelist enabled (rpc-server.c:1217)
2020-01-01T23:46:05+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:46:05.102] RPC Server Password required (rpc-server.c:1220)
2020-01-01T23:46:05+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:46:05.102] UDP Couldn't bind IPv4 socket (tr-udp.c:271)
2020-01-01T23:46:05+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:46:05.102] DHT Reusing old id (tr-dht.c:307)
2020-01-01T23:46:05+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:46:05.103] Using settings from "/config" (daemon.c:528)
2020-01-01T23:46:05+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:46:05.103] transmission-daemon requiring authentication (daemon.c:554)
2020-01-01T23:46:05+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:46:05.103] Blocklist "blocklist.bin" contains 409833 entries (blocklist.c:100)
2020-01-01T23:46:05+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:46:05.104] Port Forwarding (NAT-PMP) initnatpmp succeeded (0) (natpmp.c:70)
2020-01-01T23:46:05+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:46:05.105] Port Forwarding (NAT-PMP) sendpublicaddressrequest succeeded (2) (natpmp.c:70)
2020-01-01T23:46:12+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:46:12.079] Port Forwarding State changed from "Not forwarded" to "Starting" (port-forwarding.c:92)
2020-01-01T23:46:13+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:46:13.079] Port Forwarding State changed from "Starting" to "???" (port-forwarding.c:92)
2020-01-01T23:46:49+01:00 localhost.hq 564356623c6f[2656]: Caught SIGTERM signal!
2020-01-01T23:46:49+01:00 localhost.hq 564356623c6f[2656]: localhost:9091/transmission/rpc/ responded: "success"
2020-01-01T23:46:49+01:00 localhost.hq 564356623c6f[2656]: [cont-finish.d] executing container finish scripts...
2020-01-01T23:46:49+01:00 localhost.hq 564356623c6f[2656]: [cont-finish.d] done.
2020-01-01T23:46:49+01:00 localhost.hq 564356623c6f[2656]: [s6-finish] waiting for services.
2020-01-01T23:46:49+01:00 localhost.hq 564356623c6f[2656]: s6-svwait: fatal: supervisor died
2020-01-01T23:46:49+01:00 localhost.hq 564356623c6f[2656]: [s6-finish] sending all processes the TERM signal.
2020-01-01T23:46:50+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:46:50.081] Reloading settings from "/config" (daemon.c:472)
2020-01-01T23:46:50+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:46:50.082] RPC Server Adding address to whitelist: 127.0.0.1 (rpc-server.c:971)
2020-01-01T23:46:50+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:46:50.083] RPC Server Adding address to whitelist: **** (rpc-server.c:971)
2020-01-01T23:46:50+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:46:50.083] RPC Server Serving RPC and Web requests on port 127.0.0.1:9091/transmission/ (rpc-server.c:1213)
2020-01-01T23:46:50+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:46:50.084] RPC Server Whitelist enabled (rpc-server.c:1217)
2020-01-01T23:46:50+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:46:50.084] RPC Server Password required (rpc-server.c:1220)
2020-01-01T23:46:50+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:46:50.085] Blocklist "blocklist.bin" contains 409833 entries (blocklist.c:100)
2020-01-01T23:46:54+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:46:54.301] DHT Not saving nodes, DHT not ready (tr-dht.c:359)
2020-01-01T23:46:54+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:46:54.302] Port Forwarding Stopped (port-forwarding.c:180)
2020-01-01T23:46:54+01:00 localhost.hq 564356623c6f[2656]: [2020-01-01 23:46:54.304] Changed open file limit from 1048576 to 1024 (fdlimit.c:380)
2020-01-01T23:46:54+01:00 localhost.hq 564356623c6f[2656]: Closing transmission session... done.

Thanks in advance :-) .

**Comment by thelamer** [comment]
I cannot replicate this : 
```
 s6-svc -t /var/run/s6/services/transmission
Caught SIGTERM signal!
root@ce2f1f6db79d:/# localhost:9091/transmission/rpc/ responded: "success"
[2020-01-02 16:10:32.874] Saved "/config/settings.json" (variant.c:1266)
```
You say `-h` we changed that some time ago to `-t`, I assume that is a typo.

 Also you have set `S6_KILL_GRACETIME` was this a debugging thing ?

**Comment by lharsfalvi** [comment]
> You say -h we changed that some time ago to -t, I assume that is a typo.

Actually, I think, this is the culprit. My script contained what I quoted ( -h ), ie. it must have been the old version of the script before commit 787d572.

Thinking it over, /config is an external volume to the container, so, /config/blocklist-update.sh is not inherently updated with the container image. I gave it a try and shut down the transmission container, moved away the blocklist-update.sh script from the config directory, then restarted the container. Lo and behold, there was a new (now: up to date) blocklist-update.sh created in the config directory. So, for me this is fixed now.

Maybe this issue report should be closed, and a new one be opened about how to deal with external files, so that they get updated when their templates in the container are updated.

As for S6_KILL_GRACETIME, yes, I found this one while looking for possible causes. I think I'll leave that now as it is, as I noticed that it usually takes more than 3 sec for transmission to exit on this machine anyway. (And I have the time... :-) )

Thank you!... :-)

**Comment by YouriT** [comment]
Personally I'm still seeing this issue.

Executing:
```shell
$ /config/blocklist-update.sh
$ ps
PID   USER     TIME  COMMAND
    1 root      0:00 s6-svscan -t0 /var/run/s6/services
   31 root      0:00 s6-supervise s6-fdholderd
  248 root      0:00 s6-supervise transmission
  249 root      0:00 s6-supervise cron
  251 root      0:00 /usr/sbin/crond -f -S -l 0 -c /etc/crontabs
  267 abc       0:11 /usr/bin/transmission-daemon -g /config -c /watch -f
  277 root      0:00 bash
  308 root      0:00 bash ./run
  311 abc       0:02 /usr/bin/transmission-daemon -g /config -c /watch -f
  317 root      0:00 ps
```

I also had /config being very old so I cleared storage and got it fresh. Hence it includes the `s6-svc -t /var/run/s6/services/transmission` change mentioned in previous comment.

Maybe as an indicator of the reason this could happen is my config file being mounted as `:ro` like so:
```
volumes:
      - ./transmission-settings.json:/config/settings.json:ro
      - /downloads:/downloads
      - transmission-config:/config
```

I'll try without the `:ro` and will let you know the outcome.
